// Smallest end-to-end inverse design on the AVBD adjoint.
//
// The repo's five demos are the only things that exercise the adjoint
// all the way through an optimiser, and every one of them is slow
// (minutes) and confounded (real meshes, contact, splines, 125-400
// steps). When the dress fails to move you cannot tell whether the
// gradient is wrong or the start point is already optimal.
//
// This is the same question with everything removable removed:
//
//   4 vertices, 4 chained steps, ONE parameter, a synthetic target
//   generated by the simulator itself at a known value.
//
// A second case then runs the dress demo's OWN parameter pair,
// k_bending and density, at the same minimum scale. Two coupled
// parameters is the only structural difference between this harness and
// the dress, so if the pair recovers here, "the machinery cannot do two
// parameters" is excluded and the dress's stall is a local optimum.
// That case is also the only check readMassGrad has.
//
// Because the target is produced by this very solver at k*, a perfect
// optimiser must reach loss 0 at k = k*. There is no modelling error
// and no local-minimum ambiguity: if it does not converge, the
// gradient is wrong. That is what the demos cannot tell us.
//
// Runs in seconds. Plain gradient descent with backtracking, not
// L-BFGS, so nothing in the optimiser can paper over a bad gradient by
// absorbing its scale.
//
// Build:
//   clang++ -std=c++17 -I<vulkan>/Include -I. \
//     test_avbd_inverse_min.cpp AvbdSolverVk.cpp -lvulkan-1

#include <cmath>
#include <cstdio>
#include <vector>

#include "AvbdSolver.h"

namespace {

constexpr uint32_t NV = 4;
constexpr int STEPS = 4;
const float kPos0[12] = {0, 0, 0, 3, 0, 0, 0, 4, 0, 3, 4, 0};
const float kMass[4] = {2, 1, 1, 1};

// Springs are excluded: their Hessian-path cotangents are known wrong
// (vbd_gather_spring_backward uses trace(v_H) instead of the
// contraction, and v_p_d omits d(hess)/d(d)). Including them would
// make this test fail for a reason it is not trying to measure.
void upload(cloth::AvbdSolver &s, const float *pos, const float *pred, float kTri) {
	s.setupMesh(NV, pos, pred, kMass, 2.0f);
	const uint32_t av[1] = {2};
	const float af[3] = {0, 4, 10}, ak[1] = {4.0f};
	s.uploadAttachments(1, av, af, ak);
	const uint32_t ti[3] = {0, 1, 2};
	const float uv[4] = {1, 0, 0, 1}, tk[1] = {kTri};
	s.uploadTriangles(1, ti, uv, tk);
	const uint32_t bi[4] = {0, 1, 2, 3};
	const float bw[4] = {1, 1, -1, -1}, bn[1] = {4}, bk[1] = {1.0f};
	s.uploadBendings(1, bi, bw, bn, bk);
}

// Roll the chain forward, returning the final state.
std::vector<float> rollout(cloth::AvbdSolver &s, float kTri,
		std::vector<std::vector<float>> *states = nullptr) {
	std::vector<float> pos(kPos0, kPos0 + 12);
	if (states) states->clear();
	for (int k = 0; k < STEPS; ++k) {
		if (states) states->push_back(pos);
		upload(s, pos.data(), pos.data(), kTri);
		if (s.step() != 0) return {};
		s.readPositions(pos);
	}
	return pos;
}

double lossAt(cloth::AvbdSolver &s, float kTri, const std::vector<float> &target) {
	const std::vector<float> x = rollout(s, kTri);
	if (x.size() != target.size()) return NAN;
	double L = 0.0;
	for (size_t i = 0; i < x.size(); ++i) {
		const double d = double(x[i]) - double(target[i]);
		L += 0.5 * d * d;
	}
	return L;
}

// Loss and analytic dL/dk together, via the chained adjoint.
double lossAndGrad(cloth::AvbdSolver &s, float kTri, const std::vector<float> &target,
		double *dL_dk) {
	std::vector<std::vector<float>> states;
	const std::vector<float> xN = rollout(s, kTri, &states);
	if (xN.empty()) return NAN;

	double L = 0.0;
	std::vector<float> adj(xN.size());
	for (size_t i = 0; i < xN.size(); ++i) {
		const double d = double(xN[i]) - double(target[i]);
		L += 0.5 * d * d;
		adj[i] = float(d);  // dL/dx_N
	}

	double g = 0.0;
	for (int k = STEPS - 1; k >= 0; --k) {
		upload(s, states[k].data(), states[k].data(), kTri);
		if (s.step() != 0) return NAN;
		if (s.stepBackward(adj.data()) != 0) return NAN;

		std::vector<float> dTriK, d0, d1;
		s.readTriGrad(dTriK, d0, d1);
		if (!dTriK.empty()) g += double(dTriK[0]);

		std::vector<float> gPos, gPred;
		s.readPositionsGrad(gPos);
		s.readPredictedGrad(gPred);
		for (size_t i = 0; i < adj.size(); ++i) {
			const double a = (i < gPos.size()) ? double(gPos[i]) : 0.0;
			const double b = (i < gPred.size()) ? double(gPred[i]) : 0.0;
			adj[i] = float(a + b);
		}
	}
	*dL_dk = g;
	return L;
}

// Gradient descent with backtracking. Deliberately primitive: a
// quasi-Newton method can converge despite a mis-scaled gradient, which
// is exactly the failure this test exists to catch.
float descend(cloth::AvbdSolver &s, const std::vector<float> &target, float k0,
		bool zeroGradient, int iters, bool verbose) {
	float k = k0;
	double step = 0.1;
	for (int it = 0; it < iters; ++it) {
		double g = 0.0;
		const double L = lossAndGrad(s, k, target, &g);
		if (!(L == L)) return NAN;
		if (zeroGradient) g = 0.0;  // falsifiability arm
		if (verbose && (it % 4 == 0 || it == iters - 1)) {
			std::printf("    iter %2d  k=%9.6f  L=%12.6g  dL/dk=%11.6g\n", it, double(k),
					L, g);
		}
		if (std::fabs(g) < 1e-12) break;
		// Backtrack until the step actually decreases the loss.
		double t = step;
		float kNext = k;
		for (int b = 0; b < 30; ++b) {
			kNext = float(double(k) - t * g);
			if (kNext < 0.05f) kNext = 0.05f;
			const double Ln = lossAt(s, kNext, target);
			if (Ln == Ln && Ln < L) break;
			t *= 0.5;
		}
		if (kNext == k) break;
		k = kNext;
		step = t * 1.5;
	}
	return k;
}


// ---- two-parameter variant, mirroring the dress ------------------
//
// The dress optimises k_CONSTRAINT_TRIANGLE_BENDING and density, and
// refuses to move. This is that same pair at minimum scale, so a
// result here separates "the machinery cannot do two parameters" from
// "the dress's start point is already optimal".
//
// density scales every vertex mass, so dL/d density = sum_i
// dL/d mass_i * baseMass_i, which readMassGrad supplies directly.

void upload2(cloth::AvbdSolver &s, const float *pos, const float *pred, float kBend,
		float density) {
	float m[4];
	for (int i = 0; i < 4; ++i) m[i] = kMass[i] * density;
	s.setupMesh(NV, pos, pred, m, 2.0f);
	const uint32_t av[1] = {2};
	const float af[3] = {0, 4, 10}, ak[1] = {4.0f};
	s.uploadAttachments(1, av, af, ak);
	const uint32_t ti[3] = {0, 1, 2};
	const float uv[4] = {1, 0, 0, 1}, tk[1] = {1.0f};
	s.uploadTriangles(1, ti, uv, tk);
	const uint32_t bi[4] = {0, 1, 2, 3};
	const float bw[4] = {1, 1, -1, -1}, bn[1] = {4}, bk[1] = {kBend};
	s.uploadBendings(1, bi, bw, bn, bk);
}

std::vector<float> rollout2(cloth::AvbdSolver &s, float kBend, float density,
		std::vector<std::vector<float>> *states = nullptr) {
	std::vector<float> pos(kPos0, kPos0 + 12);
	if (states) states->clear();
	for (int k = 0; k < STEPS; ++k) {
		if (states) states->push_back(pos);
		upload2(s, pos.data(), pos.data(), kBend, density);
		if (s.step() != 0) return {};
		s.readPositions(pos);
	}
	return pos;
}

double loss2(cloth::AvbdSolver &s, float kBend, float density,
		const std::vector<float> &target) {
	const std::vector<float> x = rollout2(s, kBend, density);
	if (x.size() != target.size()) return NAN;
	double L = 0.0;
	for (size_t i = 0; i < x.size(); ++i) {
		const double d = double(x[i]) - double(target[i]);
		L += 0.5 * d * d;
	}
	return L;
}

double lossAndGrad2(cloth::AvbdSolver &s, float kBend, float density,
		const std::vector<float> &target, double *dK, double *dRho) {
	std::vector<std::vector<float>> states;
	const std::vector<float> xN = rollout2(s, kBend, density, &states);
	if (xN.empty()) return NAN;

	double L = 0.0;
	std::vector<float> adj(xN.size());
	for (size_t i = 0; i < xN.size(); ++i) {
		const double d = double(xN[i]) - double(target[i]);
		L += 0.5 * d * d;
		adj[i] = float(d);
	}

	double gK = 0.0, gRho = 0.0;
	for (int k = STEPS - 1; k >= 0; --k) {
		upload2(s, states[k].data(), states[k].data(), kBend, density);
		if (s.step() != 0) return NAN;
		if (s.stepBackward(adj.data()) != 0) return NAN;

		std::vector<float> dN, dBK, dBL;
		s.readBendGrad(dN, dBK, dBL);
		if (!dBK.empty()) gK += double(dBK[0]);

		std::vector<float> dMass;
		s.readMassGrad(dMass);
		for (uint32_t v = 0; v < NV && v < dMass.size(); ++v) {
			gRho += double(dMass[v]) * double(kMass[v]);
		}

		std::vector<float> gPos, gPred;
		s.readPositionsGrad(gPos);
		s.readPredictedGrad(gPred);
		for (size_t i = 0; i < adj.size(); ++i) {
			const double a = (i < gPos.size()) ? double(gPos[i]) : 0.0;
			const double b = (i < gPred.size()) ? double(gPred[i]) : 0.0;
			adj[i] = float(a + b);
		}
	}
	*dK = gK;
	*dRho = gRho;
	return L;
}

}  // namespace

int main(int argc, char **argv) {
	const char *dir = (argc > 1) ? argv[1] : ".";
	cloth::AvbdSolver solver(dir);
	if (!solver.ok()) {
		std::printf("test_avbd_inverse_min: construction failed\n");
		return 1;
	}

	const float kTruth = 2.0f;
	const float kStart = 0.5f;

	// Target generated by this solver at k*, so loss 0 is attainable
	// exactly and any failure to converge is the gradient's fault.
	const std::vector<float> target = rollout(solver, kTruth);
	if (target.empty()) {
		std::printf("test_avbd_inverse_min: target rollout failed\n");
		return 1;
	}

	std::printf("test_avbd_inverse_min: recover k_tri from a synthetic target\n");
	std::printf("  %u verts, %d chained steps, truth k*=%.3f, start k=%.3f\n\n", NV,
			STEPS, double(kTruth), double(kStart));

	std::printf("  gradient descent on the AVBD adjoint:\n");
	const float kFit = descend(solver, target, kStart, false, 40, true);
	const double err = std::fabs(double(kFit) - double(kTruth));
	std::printf("    -> k = %.6f  (truth %.3f, abs err %.3g)\n\n", double(kFit),
			double(kTruth), err);

	// Falsifiability: with the gradient forced to zero the same loop
	// must NOT recover k. If it does, the optimiser is finding the
	// answer on its own and this test proves nothing about the adjoint.
	std::printf("  falsifiability (gradient forced to zero):\n");
	const float kNull = descend(solver, target, kStart, true, 40, false);
	const double errNull = std::fabs(double(kNull) - double(kTruth));
	std::printf("    -> k = %.6f  (abs err %.3g)  %s\n\n", double(kNull), errNull,
			errNull > 0.1 ? "stays put, as it must" : "BAD: converged without a gradient");

	if (errNull <= 0.1) {
		std::printf("test_avbd_inverse_min: ABORT -- the zero-gradient arm also\n"
					"converged, so this test cannot attribute success to the\n"
					"adjoint.\n");
		return 1;
	}
	if (err > 0.05) {
		std::printf("test_avbd_inverse_min: FAILED -- did not recover k* (err %.3g).\n"
					"The target came from this solver, so a correct gradient must\n"
					"reach it; this is the adjoint, not a local minimum.\n",
				err);
		return 1;
	}
	// --- the dress's own parameter pair, at minimum scale -----------
	//
	// The dress optimises k_bending and density together and does not
	// move. Two parameters is the one structural difference from the
	// single-parameter case above, so run exactly that pair here. If it
	// recovers, "the machinery cannot do two parameters" is excluded and
	// the dress is sitting at a local optimum.
	{
		const float bTruth = 1.5f, rTruth = 1.25f;
		const float bStart = 0.4f, rStart = 2.5f;
		const std::vector<float> tgt2 = rollout2(solver, bTruth, rTruth);
		if (tgt2.empty()) {
			std::printf("2-param target rollout failed\n");
			return 1;
		}
		std::printf("  two parameters (k_bend, density), the dress's pair:\n");
		std::printf("    truth (%.3f, %.3f), start (%.3f, %.3f)\n", double(bTruth),
				double(rTruth), double(bStart), double(rStart));

		float b = bStart, r = rStart;
		double step = 0.05;
		for (int it = 0; it < 60; ++it) {
			double gB = 0.0, gR = 0.0;
			const double L = lossAndGrad2(solver, b, r, tgt2, &gB, &gR);
			if (!(L == L)) break;
			if (it % 10 == 0 || it == 59) {
				std::printf("    iter %2d  k=%8.5f rho=%8.5f  L=%11.5g  g=(%9.4g,%9.4g)\n",
						it, double(b), double(r), L, gB, gR);
			}
			if (std::sqrt(gB * gB + gR * gR) < 1e-10) break;
			double t = step;
			float bN = b, rN = r;
			bool moved = false;
			for (int k = 0; k < 40; ++k) {
				bN = float(double(b) - t * gB);
				rN = float(double(r) - t * gR);
				if (bN < 0.02f) bN = 0.02f;
				if (rN < 0.02f) rN = 0.02f;
				const double Ln = loss2(solver, bN, rN, tgt2);
				if (Ln == Ln && Ln < L) { moved = true; break; }
				t *= 0.5;
			}
			if (!moved) break;
			b = bN; r = rN;
			step = t * 1.5;
		}
		const double eB = std::fabs(double(b) - double(bTruth));
		const double eR = std::fabs(double(r) - double(rTruth));
		std::printf("    -> k=%.5f (err %.3g)  rho=%.5f (err %.3g)\n\n", double(b), eB,
				double(r), eR);
		if (eB > 0.05 || eR > 0.05) {
			std::printf("test_avbd_inverse_min: FAILED -- the 2-parameter case did not\n"
						"recover its synthetic target. Two coupled parameters is then a\n"
						"real limitation, and the dress's stall needs no other\n"
						"explanation.\n");
			return 1;
		}
	}

	std::printf("test_avbd_inverse_min: OK -- recovered k* to %.3g, and the\n"
				"zero-gradient arm did not, and the dress's own (k_bend, density)\n"
				"pair recovers too. The adjoint can drive an optimiser end to end.\n",
			err);
	return 0;
}
